import { Input, Segmented } from 'antd';
import { useEffect, useState } from 'react';
import styles from './index.module.css';
const gugong = [
  { name: '黄白游', color: '#FFF799' },
  { name: '松花', color: '#FFEE6F' },
  { name: '缃叶', color: '#ECD452' },
  { name: '苍黄', color: '#B6A014' },
  { name: '天缥', color: '#D5EBE1' },
  { name: '沧浪', color: '#B1D5C8' },
  { name: '苍筤', color: '#99BCAC' },
  { name: '缥碧', color: '#80A492' },
  { name: '流黄', color: '#8B7042' },
  { name: '栗壳', color: '#775039' },
  { name: '龙战', color: '#5F4321' },
  { name: '青骊', color: '#422517' },
  { name: '海天霞', color: '#F3A694' },
  { name: '缙云', color: '#EE7959' },
  { name: '纁黄', color: '#BA5140' },
  { name: '珊瑚赫', color: '#C12C1F' },
  { name: '盈盈', color: '#F9D3E3' },
  { name: '水红', color: '#ECB0C1' },
  { name: '苏梅', color: '#DD7694' },
  { name: '紫茎屏风', color: '#A76283' },
  { name: '葭灰', color: '#BEB1AA' },
  { name: '黄埃', color: '#B49273' },
  { name: '老僧衣', color: '#A46244' },
  { name: '玄天', color: '#6B5458' },
  { name: '黄河琉璃', color: '#E5A84B' },
  { name: '库金', color: '#E18A3B' },
  { name: '缊韨', color: '#984F31' },
  { name: '紫瓯', color: '#7C461E' },
  { name: '欧碧', color: '#C0D695' },
  { name: '春辰', color: '#A9BE7B' },
  { name: '碧山', color: '#779649' },
  { name: '青青', color: '#4F6F46     ' },
  { name: '赤缇', color: '#BA5B49' },
  { name: '朱草', color: '#A64036' },
  { name: '綪茷', color: '#9E2A22' },
  { name: '顺圣', color: '#7C191E' },
  { name: '桃夭', color: '#F6BEC8' },
  { name: '杨妃', color: '#F091A0' },
  { name: '长春', color: '#DC6B82' },
  { name: '牙绯', color: '#C35C5D' },
  { name: '黄栗留', color: '#FEDC5E' },
  { name: '栀子', color: '#FAC03D' },
  { name: '黄不老', color: '#DB9B34' },
  { name: '柘黄', color: '#C67915' },
  { name: '青鸾', color: '#9AA7B1' },
  { name: '菘蓝', color: '#6B798E' },
  { name: '青黛', color: '#45465E' },
  { name: '绀蝶', color: '#2C2F3B' },
  { name: '皦玉', color: '#EBEEE8' },
  { name: '吉量', color: '#EBEDDF' },
  { name: '韶粉', color: '#E0E0D0' },
  { name: '霜地', color: '#C7C6B6' },
  { name: '夏籥', color: '#D2AF9D' },
  { name: '紫磨金', color: '#BC836B' },
  { name: '檀色', color: '#B26D5D' },
  { name: '赭罗', color: '#9A6655' },
  { name: '黄丹', color: '#EA5514' },
  { name: '洛神珠', color: '#D23918' },
  { name: '丹雘', color: '#C8161D' },
  { name: '水华朱', color: '#A72126' },
  { name: '青冥', color: '#3271AE' },
  { name: '青雘', color: '#007175' },
  { name: '青緺', color: '#284852' },
  { name: '骐驎', color: '#12264F' },
  { name: '紫蒲', color: '#A6559D' },
  { name: '赪紫', color: '#8A1874' },
  { name: '齐紫', color: '#6C216D' },
  { name: '凝夜紫', color: '#422256' },
  { name: '冻缥', color: '#BEC2B3' },
  { name: '春碧', color: '#9D9D82' },
  { name: '执大象', color: '#919177' },
  { name: '苔古', color: '#79836C' },
  { name: '香炉紫烟', color: '#D3CCD6' },
  { name: '紫菂', color: '#9B8EA9' },
  { name: '拂紫绵', color: '#7E527F' },
  { name: '三公子', color: '#663D74' },
  { name: '琅玕紫', color: '#CB5C83' },
  { name: '红踯躅', color: '#B83570' },
  { name: '魏红', color: '#A73766' },
  { name: '魏紫', color: '#903754' },
  { name: '昌荣', color: '#DCC7E1' },
  { name: '紫薄汗', color: '#BBA1CB' },
  { name: '茈藐', color: '#A67EB7' },
  { name: '紫紶', color: '#7D5284' },
  { name: '苍葭', color: '#A8BF8F' },
  { name: '庭芜绿', color: '#68945C' },
  { name: '翠微', color: '#4C8045' },
  { name: '翠虬', color: '#446A37' },
  { name: '碧落', color: '#AED0EE' },
  { name: '挼蓝', color: '#6E9BC5' },
  { name: '青雀头黛', color: '#354E6B' },
  { name: '螺子黛', color: '#13393E' },
  { name: '露褐', color: '#BD8253' },
  { name: '檀褐', color: '#945635' },
  { name: '緅絺', color: '#804C2E' },
  { name: '目童子', color: '#5B3222' },
  { name: '青粲', color: '#C3D94E' },
  { name: '翠缥', color: '#B7D332' },
  { name: '人籁', color: '#9EBC19' },
  { name: '水龙吟', color: '#84A729' },
  { name: '地籁', color: '#DFCEB4' },
  { name: '大块', color: '#BFA782' },
  { name: '养生主', color: '#B49B7F' },
  { name: '大云', color: '#94784F' },
  { name: '溶溶月', color: '#BEC2BC' },
  { name: '绍衣', color: '#A8A19C' },
  { name: '石莲褐', color: '#92897B' },
  { name: '黑朱', color: '#70695D' },
  { name: '朱颜酡', color: '#F29A76' },
  { name: '苕荣', color: '#ED6D3D' },
  { name: '檎丹', color: '#E94829' },
  { name: '丹罽', color: '#E60012' },
  { name: '彤管', color: '#E2A2AC' },
  { name: '渥赭', color: '#DD6B7B' },
  { name: '唇脂', color: '#C25160' },
  { name: '朱孔阳', color: '#B81A35' },
  { name: '石发', color: '#6A8D52' },
  { name: '漆姑', color: '#5D8351' },
  { name: '芰荷', color: '#4F794A' },
  { name: '官绿', color: '#2A6E3F' },
  { name: '仙米', color: '#D4C9AA' },
  { name: '黄螺', color: '#B4A379' },
  { name: '降真香', color: '#9E8358' },
  { name: '远志', color: '#81663B' },
  { name: '嫩鹅黄', color: '#F2C867' },
  { name: '鞠衣', color: '#D3A237' },
  { name: '郁金裙', color: '#D08635' },
  { name: '黄流', color: '#9F6027' },
  { name: '筠雾', color: '#D5D1AE' },
  { name: '瓷秘', color: '#BFC096' },
  { name: '琬琰', color: '#A9A886' },
  { name: '青圭', color: '#92905D' },
  { name: '鸣珂', color: '#B3B59C' },
  { name: '青玉案', color: '#A8B092' },
  { name: '出岫', color: '#A9A773' },
  { name: '风入松', color: '#868C4E' },
  { name: '如梦令', color: '#DDBB99' },
  { name: '芸黄', color: '#D2A36C' },
  { name: '金埒', color: '#BE9457' },
  { name: '雌黄', color: '#B4884D' },
  { name: '曾青', color: '#535164' },
  { name: '䒌靘', color: '#454659' },
  { name: '璆琳', color: '#343041' },
  { name: '瑾瑜', color: '#1E2732' },
  { name: '赩炽', color: '#CB523E' },
  { name: '石榴裙', color: '#B13B2E' },
  { name: '朱湛', color: '#95302E' },
  { name: '大繎', color: '#822327' },
  { name: '月魄', color: '#B2B6B6' },
  { name: '不皂', color: '#A7AAA1' },
  { name: '雷雨垂', color: '#7A7B78' },
  { name: '石涅', color: '#686A67' },
  { name: '扶光', color: '#F0C2A2' },
  { name: '椒房', color: '#DB9C5E' },
  { name: '红友', color: '#D9883D' },
  { name: '光明砂', color: '#CC5D20' },
  { name: '山矾', color: '#F5F3F2' },
  { name: '玉頩', color: '#EAE5E3' },
  { name: '二目鱼', color: '#DFE0D9' },
  { name: '明月珰', color: '#D4D3CA' },
  { name: '骍刚', color: '#F5B087' },
  { name: '赪霞', color: '#F18F60' },
  { name: '赪尾', color: '#EF845D' },
  { name: '朱柿', color: '#ED6D46' },
  { name: '天球', color: '#E0DFC6' },
  { name: '行香子', color: '#BFB99C' },
  { name: '王刍', color: '#A99F70' },
  { name: '荩箧', color: '#877D52' },
  { name: '赤灵', color: '#954024' },
  { name: '丹秫', color: '#873424' },
  { name: '木兰', color: '#662B1F' },
  { name: '麒麟竭', color: '#4C1E1A' },
  { name: '柔蓝', color: '#106898' },
  { name: '碧城', color: '#12507B' },
  { name: '蓝采和', color: '#06436F' },
  { name: '帝释青', color: '#003460' },
  { name: '夕岚', color: '#E3ADB9' },
  { name: '雌霓', color: '#CF929E' },
  { name: '绛纱', color: '#B27777' },
  { name: '茹藘', color: '#A35F65' },
  { name: '葱青', color: '#EDF1BB' },
  { name: '少艾', color: '#E3EB98' },
  { name: '绮钱', color: '#D8DE8A' },
  { name: '翠樽', color: '#CDD171' },
  { name: '石蜜', color: '#D4BF89' },
  { name: '沙饧', color: '#BFA670' },
  { name: '巨吕', color: '#AA8E59' },
  { name: '吉金', color: '#896D47' },
  { name: '山岚', color: '#BED2BB' },
  { name: '渌波', color: '#9BB496' },
  { name: '青楸', color: '#81A380' },
  { name: '菉竹', color: '#698E6A' },
  { name: '窃蓝', color: '#88ABDA' },
  { name: '监德', color: '#6F94CD' },
  { name: '苍苍', color: '#5976BA' },
  { name: '群青', color: '#2E59A7' },
  { name: '白青', color: '#98B6C2' },
  { name: '竹月', color: '#7F9FAF' },
  { name: '空青', color: '#66889E' },
  { name: '太师青', color: '#547689' },
  { name: '缟羽', color: '#EFEFEF' },
  { name: '香皮', color: '#D8D1C5' },
  { name: '云母', color: '#C6BEB1' },
  { name: '佩玖', color: '#AC9F8A' },
  { name: '麹尘', color: '#C0D09D' },
  { name: '绿沈', color: '#938F4C' },
  { name: '绞衣', color: '#7F754C' },
  { name: '素綦', color: '#595333' },
  { name: '退红', color: '#F0CFE3' },
  { name: '樱花', color: '#E4B8D5' },
  { name: '丁香', color: '#CE93BF' },
  { name: '木槿', color: '#BA79B1' },
  { name: '余白', color: '#C9CFC1' },
  { name: '兰苕', color: '#A8B78C' },
  { name: '碧滋', color: '#90A07D' },
  { name: '葱倩', color: '#6C8650' },
  { name: '云门', color: '#A2D2E2' },
  { name: '西子', color: '#87C0CA' },
  { name: '天水碧', color: '#5AA4AE' },
  { name: '法翠', color: '#108B96' },
  { name: '桑蕾', color: '#EAD89A' },
  { name: '太一余粮', color: '#D5B45C' },
  { name: '秋香', color: '#BF9C46' },
  { name: '老茯神', color: '#AA8534' },
  { name: '凝脂', color: '#F5F2E9' },
  { name: '玉色', color: '#EAE4D1' },
  { name: '黄润', color: '#DFD6B8' },
  { name: '缣缃', color: '#D5C8A0' },
  { name: '蕉月', color: '#86908A' },
  { name: '千山翠', color: '#6B7D73' },
  { name: '结绿', color: '#555F4D' },
  { name: '绿云', color: '#45493D' },
  { name: '藕丝秋半', color: '#D3CBC5' },
  { name: '苍烟落照', color: '#C8B5B3' },
  { name: '红藤杖', color: '#928187' },
  { name: '紫鼠', color: '#594C57' },
  { name: '黄粱', color: '#C4B798' },
  { name: '蒸栗', color: '#A58A5F' },
  { name: '射干', color: '#7C623F' },
  { name: '油葫芦', color: '#644D31' },
  { name: '卵色', color: '#D5E3D4' },
  { name: '葭菼', color: '#CAD7C5' },
  { name: '冰台', color: '#BECAB7' },
  { name: '青古', color: '#B3BDA9' },
  { name: '栾华', color: '#C0AD5E' },
  { name: '大赤', color: '#AA9649' },
  { name: '佛赤', color: '#8F3D2C' },
  { name: '蜜褐', color: '#683632' },
  { name: '孔雀蓝', color: '#4994C4' },
  { name: '吐绶蓝', color: '#4182A4' },
  { name: '鱼师青', color: '#32788A' },
  { name: '软翠', color: '#006D87' },
  { name: '浅云', color: '#EAEEF1' },
  { name: '素采', color: '#D4DDE1' },
  { name: '影青', color: '#BDCBD2' },
  { name: '逍遥游', color: '#B2BFC3' },
  { name: '醽醁', color: '#A6BAB1' },
  { name: '翠涛', color: '#819D8E' },
  { name: '青梅', color: '#778A77' },
  { name: '翕赩', color: '#5F766A' },
  { name: '九斤黄', color: '#DDB078' },
  { name: '杏子', color: '#DA9233' },
  { name: '媚蝶', color: '#BC6E37' },
  { name: '韎韐', color: '#9F5221' },
  { name: '东方既白', color: '#8BA3C7' },
  { name: '绀宇', color: '#003D74' },
  { name: '佛头青', color: '#19325F' },
  { name: '花青', color: '#1A2847' },
  { name: '弗肯红', color: '#ECD9C7' },
  { name: '赤璋', color: '#E1C199' },
  { name: '茧色', color: '#C6A268' },
  { name: '密陀僧', color: '#B3934B' },
  { name: '银朱', color: '#D12920' },
  { name: '胭脂虫', color: '#AB1D22' },
  { name: '朱樱', color: '#8F1D22' },
  { name: '爵头', color: '#631216' },
  { name: '甘石', color: '#BDB2B2' },
  { name: '迷楼灰', color: '#91828F' },
  { name: '鸦雏', color: '#6A5B6D' },
  { name: '烟墨', color: '#5C4F55' },
  { name: '十样锦', color: '#F8C6B5' },
  { name: '檀唇', color: '#DA9E8C' },
  { name: '琼琚', color: '#D77F66' },
  { name: '棠梨', color: '#B15A43' },
  { name: '蜜合', color: '#DFD7C2' },
  { name: '假山南', color: '#D4C1A6' },
  { name: '紫花布', color: '#BEA78B' },
  { name: '沉香', color: '#99806C' },
  { name: '半见', color: '#FFFBC7' },
  { name: '女贞黄', color: '#F7EEAD' },
  { name: '绢纨', color: '#ECE093' },
  { name: '姜黄', color: '#D6C560' },
  { name: '繱犗', color: '#88BFB8' },
  { name: '二绿', color: '#5DA39D' },
  { name: '铜青', color: '#3D8E86' },
  { name: '石绿', color: '#206864' },
  { name: '黄琮', color: '#9E8C6B' },
  { name: '茶色', color: '#887657' },
  { name: '伽罗', color: '#6D5C3D' },
  { name: '苍艾', color: '#5A4B3B' },
  { name: '藕丝褐', color: '#A88787' },
  { name: '葡萄褐', color: '#9E696D' },
  { name: '苏方', color: '#81474C' },
  { name: '福色', color: '#662B2F' },
  { name: '龙膏烛', color: '#DE82A7' },
  { name: '黪紫', color: '#CC73A0' },
  { name: '胭脂水', color: '#B95A89' },
  { name: '胭脂紫', color: '#B0436F' },
  { name: '小红', color: '#E67762' },
  { name: '岱赭', color: '#DD6B4F' },
  { name: '鹤顶红', color: '#D24735' },
  { name: '朱殷', color: '#B93A26' },
  { name: '月白', color: '#D4E5EF' },
  { name: '星郎', color: '#BCD4E7' },
  { name: '晴山', color: '#A3BBDB' },
  { name: '品月', color: '#8AABCC' },
  { name: '明茶褐', color: '#9E8368' },
  { name: '荆褐', color: '#906C4A' },
  { name: '驼褐', color: '#7C5B3E' },
  { name: '椒褐', color: '#72453A' },
  { name: '粉米', color: '#EFC4CE' },
  { name: '縓缘', color: '#CE8892' },
  { name: '美人祭', color: '#C35C6A' },
  { name: '鞓红', color: '#B04552' },
  { name: '米汤娇', color: '#EEEAD9' },
  { name: '草白', color: '#BFC1A9' },
  { name: '玄校', color: '#A9A082' },
  { name: '綟绶', color: '#756C4B' },
  { name: '雀梅', color: '#788A6F' },
  { name: '油绿', color: '#5D7259' },
  { name: '莓莓', color: '#4E6548' },
  { name: '螺青', color: '#3F503B' },
  { name: '暮山紫', color: '#A4ABD6' },
  { name: '紫苑', color: '#757CBB' },
  { name: '优昙瑞', color: '#615EA8' },
  { name: '延维', color: '#4A4B9D' },
  { name: '银红', color: '#E7CAD3' },
  { name: '莲红', color: '#D9A0B3' },
  { name: '紫梅', color: '#BB7A8C' },
  { name: '紫矿', color: '#9E4E56' },
  { name: '咸池', color: '#DAA9A9' },
  { name: '红䵂', color: '#CD7372' },
  { name: '蚩尤旗', color: '#A85858' },
  { name: '霁红', color: '#7C4449' },
  { name: '莺儿', color: '#EBE1A9' },
  { name: '禹余粮', color: '#E1D279' },
  { name: '姚黄', color: '#D6BC46' },
  { name: '蛾黄', color: '#BE8A2F' },
  { name: '濯绛', color: '#796860' },
  { name: '墨黪', color: '#585248' },
  { name: '驖骊', color: '#46433B' },
  { name: '京元', color: '#31322C' },
  { name: '酂白', color: '#F6F9E4' },
  { name: '断肠', color: '#ECEBC2' },
  { name: '田赤', color: '#E1D384' },
  { name: '黄封', color: '#CAB272' },
  { name: '丁香褐', color: '#BD9683' },
  { name: '棠梨褐', color: '#955A42' },
  { name: '朱石栗', color: '#81492C' },
  { name: '枣褐', color: '#68361A' },
  { name: '秋蓝', color: '#7D929F' },
  { name: '育阳染', color: '#576470' },
  { name: '霁蓝', color: '#3C4654' },
  { name: '獭见', color: '#151D29' },
  { name: '井天', color: '#A4C9CC' },
  { name: '正青', color: '#6CA8AF' },
  { name: '扁青', color: '#509296' },
  { name: '䌦色', color: '#226B68' },
  { name: '紫府', color: '#995D7F' },
  { name: '地血', color: '#814662' },
  { name: '芥拾紫', color: '#602641' },
  { name: '油紫', color: '#420B2F' },
  { name: '骨缥', color: '#EBE3C7' },
  { name: '青白玉', color: '#CAC5A0' },
  { name: '绿豆褐', color: '#92896B' },
  { name: '冥色', color: '#665F4D' },
  { name: '肉红', color: '#DDC5B8' },
  { name: '珠子褐', color: '#BEA89D' },
  { name: '鹰背褐', color: '#8F6D5F' },
  { name: '麝香褐', color: '#694B3C' },
  { name: '石英', color: '#C8B6BB' },
  { name: '银褐', color: '#9C8D9B' },
  { name: '烟红', color: '#9D858F' },
  { name: '紫诰', color: '#76555D' },
];

const chantong = [
  { name: '精白', color: '#ffffff' },
  { name: '银白', color: '#e9e7ef' },
  { name: '铅白', color: '#f0f0f4' },
  { name: '霜色', color: '#e9f1f6' },
  { name: '雪白', color: '#f0fcff' },
  { name: '莹白', color: '#e3f9fd' },
  { name: '月白', color: '#d6ecf0' },
  { name: '象牙白', color: '#fffbf0' },
  { name: '缟', color: '#f2ecde' },
  { name: '鱼肚白', color: '#fcefe8' },
  { name: '白粉', color: '#fff2df' },
  { name: '荼白', color: '#f3f9f1' },
  { name: '鸭卵青', color: '#e0eee8' },
  { name: '素', color: '#e0f0e9' },
  { name: '青白', color: '#c0ebd7' },
  { name: '蟹壳青', color: '#bbcdc5' },
  { name: '花白', color: '#c2ccd0' },
  { name: '老银', color: '#bacac6' },
  { name: '灰色', color: '#808080' },
  { name: '苍色', color: '#75878a' },
  { name: '水色', color: '#88ada6' },
  { name: '黝', color: '#6b6882' },
  { name: '乌色', color: '#725e82' },
  { name: '玄青', color: '#3d3b4f' },
  { name: '乌黑', color: '#392f41' },
  { name: '黎', color: '#75664d' },
  { name: '黧', color: '#5d513c' },
  { name: '黝黑', color: '#665757' },
  { name: '缁色', color: '#493131' },
  { name: '煤黑', color: '#312520' },
  { name: '漆黑', color: '#161823' },
  { name: '黑色', color: '#000000' },
  { name: '樱草色', color: '#eaff56' },
  { name: '鹅黄', color: '#fff143' },
  { name: '鸭黄', color: '#faff72' },
  { name: '杏黄', color: '#ffa631' },
  { name: '橙黄', color: '#ffa400' },
  { name: '橙色', color: '#fa8c35' },
  { name: '杏红', color: '#ff8c31' },
  { name: '橘黄', color: '#ff8936' },
  { name: '橘红', color: '#ff7500' },
  { name: '藤黄', color: '#ffb61e' },
  { name: '姜黄', color: '#ffc773' },
  { name: '雌黄', color: '#ffc64b' },
  { name: '赤金', color: '#f2be45' },
  { name: '缃色', color: '#f0c239' },
  { name: '雄黄', color: '#e9bb1d' },
  { name: '秋香色', color: '#d9b611' },
  { name: '金色', color: '#eacd76' },
  { name: '牙色', color: '#eedeb0' },
  { name: '枯黄', color: '#d3b17d' },
  { name: '黄栌', color: '#e29c45' },
  { name: '乌金', color: '#a78e44' },
  { name: '昏黄', color: '#c89b40' },
  { name: '棕黄', color: '#ae7000' },
  { name: '琥珀', color: '#ca6924' },
  { name: '棕色', color: '#b25d25' },
  { name: '茶色', color: '#b35c44' },
  { name: '棕红', color: '#9b4400' },
  { name: '赭', color: '#9c5333' },
  { name: '松花色', color: '#bce672' },
  { name: '柳黄', color: '#c9dd22' },
  { name: '嫩绿', color: '#bddd22' },
  { name: '柳绿', color: '#afdd22' },
  { name: '葱黄', color: '#a3d900' },
  { name: '葱绿', color: '#9ed900' },
  { name: '豆绿', color: '#9ed048' },
  { name: '豆青', color: '#96ce54' },
  { name: '油绿', color: '#00bc12' },
  { name: '葱倩', color: '#0eb83a' },
  { name: '葱青', color: '#0eb83a' },
  { name: '青葱', color: '#0aa344' },
  { name: '石绿', color: '#16a951' },
  { name: '松柏绿', color: '#21a675' },
  { name: '松花绿', color: '#057748' },
  { name: '绿沈', color: '#0c8918' },
  { name: '绿色', color: '#00e500' },
  { name: '草绿', color: '#40de5a' },
  { name: '青翠', color: '#00e079' },
  { name: '青色', color: '#00e09e' },
  { name: '翡翠色', color: '#3de1ad' },
  { name: '碧绿', color: '#2add9c' },
  { name: '玉色', color: '#2edfa3' },
  { name: '缥', color: '#7fecad' },
  { name: '艾绿', color: '#a4e2c6' },
  { name: '石青', color: '#7bcfa6' },
  { name: '碧色', color: '#1bd1a5' },
  { name: '青碧', color: '#48c0a3' },
  { name: '铜绿', color: '#549688' },
  { name: '竹青', color: '#789262' },
  { name: '墨灰', color: '#758a99' },
  { name: '墨色', color: '#50616d' },
  { name: '鸦青', color: '#424c50' },
  { name: '黯', color: '#41555d' },
  { name: '朱砂', color: '#ff461f' },
  { name: '火红', color: '#ff2d51' },
  { name: '朱膘', color: '#f36838' },
  { name: '妃色', color: '#ed5736' },
  { name: '洋红', color: '#ff4777' },
  { name: '品红', color: '#f00056' },
  { name: '粉红', color: '#ffb3a7' },
  { name: '桃红', color: '#f47983' },
  { name: '海棠红', color: '#db5a6b' },
  { name: '樱桃色', color: '#c93756' },
  { name: '酡颜', color: '#f9906f' },
  { name: '银红', color: '#f05654' },
  { name: '大红', color: '#ff2121' },
  { name: '石榴红', color: '#f20c00' },
  { name: '绛紫', color: '#8c4356' },
  { name: '绯红', color: '#c83c23' },
  { name: '胭脂', color: '#9d2933' },
  { name: '朱红', color: '#ff4c00' },
  { name: '丹', color: '#ff4e20' },
  { name: '彤', color: '#f35336' },
  { name: '酡红', color: '#dc3023' },
  { name: '炎', color: '#ff3300' },
  { name: '茜色', color: '#cb3a56' },
  { name: '绾', color: '#a98175' },
  { name: '檀', color: '#b36d61' },
  { name: '嫣红', color: '#ef7a82' },
  { name: '洋红', color: '#ff0097' },
  { name: '枣红', color: '#c32136' },
  { name: '殷红', color: '#be002f' },
  { name: '赫赤', color: '#c91f37' },
  { name: '银朱', color: '#bf242a' },
  { name: '赤', color: '#c3272b' },
  { name: '胭脂', color: '#9d2933' },
  { name: '蔚蓝', color: '#70f3ff' },
  { name: '蓝', color: '#44cef6' },
  { name: '碧蓝', color: '#3eede7' },
  { name: '石青', color: '#1685a9' },
  { name: '靛青', color: '#177cb0' },
  { name: '靛蓝', color: '#065279' },
  { name: '花青', color: '#003472' },
  { name: '宝蓝', color: '#4b5cc4' },
  { name: '蓝灰色', color: '#a1afc9' },
  { name: '藏青', color: '#2e4e7e' },
  { name: '藏蓝', color: '#3b2e7e' },
  { name: '黛', color: '#4a4266' },
  { name: '黛绿', color: '#426666' },
  { name: '黛蓝', color: '#425066' },
  { name: '黛紫', color: '#574266' },
  { name: '紫色', color: '#8d4bbb' },
  { name: '紫酱', color: '#815463' },
  { name: '酱紫', color: '#815476' },
  { name: '紫檀', color: '#4c221b' },
  { name: '绀青', color: '#003371' },
  { name: '紫棠', color: '#56004f' },
  { name: '青莲', color: '#801dae' },
  { name: '群青', color: '#4c8dae' },
  { name: '雪青', color: '#b0a4e3' },
  { name: '丁香色', color: '#cca4e3' },
  { name: '藕色', color: '#edd1d8' },
  { name: '藕荷色', color: '#e4c6d0' },
  { name: '驼色', color: '#a88462' },
  { name: '秋色', color: '#896c39' },
  { name: '棕绿', color: '#827100' },
  { name: '褐色', color: '#6e511e' },
  { name: '棕黑', color: '#7c4b00' },
  { name: '赭色', color: '#955539' },
  { name: '赭石', color: '#845a33' },
  { name: '栗色', color: '#60281e' },
  { name: '玄色', color: '#622a1d' },
];

function hexToRgb(hex: string) {
  return (
    'rgb(' +
    parseInt('0x' + hex.slice(1, 3)) +
    ',' +
    parseInt('0x' + hex.slice(3, 5)) +
    ',' +
    parseInt('0x' + hex.slice(5, 7)) +
    ')'
  );
}

const colorMap = [
  {
    key: '故宫色',
    value: 'gugong',
    children: gugong,
  },
  {
    key: '中国传统色',
    value: 'chantong',
    children: chantong,
  },
];
const Color = () => {
  const [colorListName, setColorListName] = useState('gugong');
  const [keyword, setKeyword] = useState('');
  const [color, setColor] = useState('#F5F2E9');
  const [colorName, setColorName] = useState('凝脂');

  useEffect(() => {
    document.title = '之之选色';
  }, [colorListName, keyword]);

  return (
    <div
      style={{
        display: 'flex',
        flexDirection: 'column',
        gap: 24,
        padding: 24,
        minWidth: '100%',
        background: color,
        transition: 'all 0.3s',
        fontFamily:
          '"Times New Roman", times, "Heti Song", serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"',
      }}
      className="entry heti"
    >
      <link rel="stylesheet" href="//unpkg.com/heti/umd/heti.min.css"></link>
      {colorName ? <h1>{colorName}</h1> : null}
      <div
        style={{
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }}
      >
        <Segmented
          value={colorListName}
          onChange={(value) => {
            setColorListName(value);
          }}
          options={colorMap.map((item) => ({
            key: item.key,
            label: item.key,
            value: item.value,
          }))}
        />
      </div>
      <Input
        placeholder="搜索颜色"
        value={keyword}
        onChange={(e) => {
          setKeyword(e.target.value);
        }}
      />
      <div className={` ${styles?.['mask-card-list']}`}>
        {colorMap
          .find((item) => item.value === colorListName)
          ?.children.filter((item) => {
            if (!keyword) {
              return true;
            }

            return item.color.includes(keyword) || item.name.includes(keyword);
          })
          .map((item) => (
            <div
              key={item.color}
              className={styles?.['mask-cards']}
              style={{
                borderRadius: 12,
                padding: 12,
                boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
                width: '100%',
                transition: 'all 0.3s',
                //@ts-ignore
                '--bg': item.color,
                backgroundColor: 'var(--bg)',
                marginBottom: 10,
              }}
              onClick={() => {
                setColor(item.color);
                setColorName(item.name);
              }}
            >
              <div style={{ color: 'color-contrast(var(--bg) vs #fff, #000)' }}>{item.name}</div>
              <div
                style={{
                  color: 'color-contrast(var(--bg) vs #fff, #000)',
                }}
              >
                {item.color?.toUpperCase()}
              </div>
              <div
                style={{
                  color: 'color-contrast(var(--bg) vs #fff, #000)',
                }}
              >
                {hexToRgb(item.color)}
              </div>
            </div>
          ))}
      </div>
    </div>
  );
};

export default Color;
